services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    container_name: laravel-app
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:16
    container_name: laravel-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  adminer:
    image: adminer
    container_name: laravel-adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
